# 07/13

#### Q. 남녀 파트너 정해주기 프로그램(zip) 
같은 수의 남녀 모임에서 파트너를 랜덤하게 정해주는 프로그램을 만들어 보세요

male = ['철수','갑돌','로미오','이몽룡','온돌']

female = ['미미','갑순','줄리엣','성춘향','평강']


In [5]:
male = ['철수','갑돌','로미오','이몽룡','온돌']
female = ['미미','갑순','줄리엣','성춘향','평강']

- male = 철수,갑돌,로미오,이몽룡,온돌
- female = 미미,갑순,줄리엣,성춘향,평강

In [ ]:
#랜덤 커플 지정 함수 

import random

def couple_match(li_1,li_2):
    try:        
        random_m=random.sample(li_1,len(li_1))
        random_f=random.sample(li_2,len(li_2))

        couple=[]
        for i in range(len(li_1)):
            couple.append((random_m[i],random_f[i]))
        return couple
    except:
        if IndexError:
            print('※경고※ 같은 수의 남녀 리스트를 입력하세요!\n')
        

couple_match(male,female)

In [28]:
#프로그래밍

male=input(">>랜덤 파트너 남자들의 이름을 ','로 분리하여 입력하세요. \nex)갑돌,갑작,갑주 \n")
female=input(">>랜덤 파트너 여자들의 이름을 ','로 분리하여 입력하세요. \nex)갑돌,갑작,갑주 \n")

male=list(male.split(','))
female=list(female.split(','))

couple_match(male, female)

>>랜덤 파트너 남자들의 이름을 ','로 분리하여 입력하세요. 
ex)갑돌,갑작,갑주 
갑돌,갑작,갑주 
>>랜덤 파트너 여자들의 이름을 ','로 분리하여 입력하세요. 
ex)갑돌,갑작,갑주 
미미,갑순,줄리엣


[('갑돌', '줄리엣'), ('갑작', '갑순'), ('갑주 ', '미미')]

In [6]:
#zip방식
def couple_match(li_1,li_2):
    try:        
        random_m=random.sample(li_1,len(li_1))
        random_f=random.sample(li_2,len(li_2))

        r_zip=zip(random_m,random_f)
        
        for i,j in enumerate(r_zip):
            print(f'{i+1}번째 매칭: {j[0]} ♥ {j[1]}')
        
    except:
        if IndexError:
            print('※경고※ 같은 수의 남녀 리스트를 입력하세요!')
    


1번째 매칭: 갑돌 ♥ 줄리엣
2번째 매칭: 로미오 ♥ 미미
3번째 매칭: 온돌 ♥ 성춘향
4번째 매칭: 이몽룡 ♥ 갑순
5번째 매칭: 철수 ♥ 평강


In [7]:
#프로그래밍

male=input(">>랜덤 파트너 남자들의 이름을 ','로 분리하여 입력하세요. \nex)갑돌,갑작,갑주 \n")
female=input(">>랜덤 파트너 여자들의 이름을 ','로 분리하여 입력하세요. \nex)갑돌,갑작,갑주 \n")

male=list(male.split(','))
female=list(female.split(','))

couple_match(male, female)


>>랜덤 파트너 남자들의 이름을 ','로 분리하여 입력하세요. 
ex)갑돌,갑작,갑주 
갑돌,갑작,갑주 
>>랜덤 파트너 여자들의 이름을 ','로 분리하여 입력하세요. 
ex)갑돌,갑작,갑주 
갑돌,갑작,갑주 
1번째 매칭: 갑돌 ♥ 갑주 
2번째 매칭: 갑주  ♥ 갑작
3번째 매칭: 갑작 ♥ 갑돌


#### Q2. 사용자가 입력한 횟수만큼 로또 번호를 출력하는 프로그램 작성하세요.(중복 금지)

In [11]:
#로또번호 개수를 입력하는 경우

#함수지정
def lotto_num(x): 
    return sorted(random.sample(list(range(1,46)),x))


In [15]:
#프로그래밍
x=int(input(">>원하시는 번호의 개수를 입력하세요\n"))
lotto_num(x)


>>원하시는 번호의 개수를 입력하세요
8


[3, 5, 14, 16, 22, 27, 29, 32]

In [18]:
#로또번호 묶음 개수를 입력하는 경우

#함수지정
def lotto_count(c):
    for i in range(c):
        time.sleep(1)
        print(f'{i+1}번째 로또번호 모음: {sorted(random.sample(list(range(1,46)),6))}')

In [19]:
#프로그래밍
x=int(input(">>원하시는 로또번호 묶음 개수를 입력하세요\n"))
        
lotto_count(x)

>>원하시는 로또번호 묶음 개수를 입력하세요
2
1번째 로또번호 모음: [1, 4, 18, 24, 26, 35]
2번째 로또번호 모음: [17, 21, 22, 23, 34, 37]


#### [도전과제] 발표자를 원하는 수만큼 랜덤하게 출력하는 프로그램 작성하기

In [58]:
#함수 정의
import random
import time

def goodluck(n):
    cakd7 = ['박영권','김현지','김덕현','변서연','한지웅','양주희','이호원','정지은',
         '이정현A','이정현B','이명진','이상윤','조승현','강유한','김영선','최애림',
         '김민섭','박혜린','윤정준','김진형','정승기','진청아','신창훈','김병석','박세희']
    
    r_s=random.sample(cakd7,n)
    for i in range(n):
        time.sleep(1)
        print(f'{i+1}번째 발표자는 "{r_s[i]}"님 입니다.')


In [59]:
#프로그래밍

n=int(input('>>발표자 수를 입력하세요.\n'))
goodluck(n)

>>발표자 수를 입력하세요.
1
1번째 발표자는 "이호원"님 입니다.


In [64]:
import random
import time

cakd7 = ['김현지','변서연','양주희','정지은','이정현A','이정현B','이명진','김영선','최애림','박혜린','진청아','박세희']


for i in range(4):
    r_s=random.sample(cakd7,3)
    time.sleep(2)
    print(f'{i+1}조 조원: {r_s}')
    for j in r_s:
        cakd7.remove(j)

1조 조원: ['박혜린', '진청아', '정지은']
2조 조원: ['이정현B', '변서연', '이정현A']
3조 조원: ['김영선', '김현지', '박세희']
4조 조원: ['양주희', '최애림', '이명진']


# 07/14

#### Q3.입력받은 문자열의 각 문자를 그 다음 문자로 변경하여 출력하세요. ex) abc->bca

In [31]:
#다음문자를 출력하는 함수

def next_text(x):
    return x[-1]+x[:-1]
            

In [32]:
x=input('>>문자를 입력하세요.\n')
print('\n')
next_text(x)

>>문자를 입력하세요.
가나다라




'라가나다'

In [5]:
#문자를 반대로 출력해주는 함수

def change(x):
    r_idx_x=sorted(list(range(len(x))),reverse=True)
    for r_idx in r_idx_x:
        print(x[r_idx],end='')       
            

In [6]:
x=input('>>문자를 입력하세요. 반대로 출력해드립니다.\n')

change(x)

>>문자를 입력하세요. 반대로 출력해드립니다.문자를 반대로
로대반 를자문

#### Q4.url에서 호스트 도메인을 추출하여 출력하세요.
- url = 'http://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=028&aid=0002334601'
- 호스트 도메인: news.naver.com

In [22]:
import re

url='http://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=028&aid=0002334601'

In [24]:
url.split('/')[2]

'news.naver.com'

In [54]:
#findall로 찾기
p=re.compile('http://([\w.]+)')
p.findall(url)

['news.naver.com']

In [58]:
#finditer로 찾기

for i in p.finditer(url):
    print(i.group(1))

news.naver.com


In [60]:
#search로 찾기

p.search(url).group(1)

'news.naver.com'

In [63]:
#match로 찾기

p.match(url).group(1)

'news.naver.com'

In [65]:
p2=re.compile('(?<=http://)(\w+)(?=/)')
p2.findall(url)

[]

#### Q5. url에서 쿼리문을 출력하기

- url에서 '?'뒤에 표시되는 문자열을 쿼리 문자열이라고 하며 변수=값 사이 &로  구분되어 나열된다.
- url = 'http://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=028&aid=0002334601'


In [7]:
import re

url = 'http://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=028&aid=0002334601'

p=re.compile('[\w./:]+[?]([\w./:=&]+)')


query=p.search(url).group(1).split('&')

for i in range(len(query)):
    print(f'{i+1}번째 쿼리문자열: {query[i]}')

1번째 쿼리문자열: mode=LSD
2번째 쿼리문자열: mid=shm
3번째 쿼리문자열: sid1=105
4번째 쿼리문자열: oid=028
5번째 쿼리문자열: aid=0002334601


#### Q6. 텍스트 파일(mydata.txt)을 읽고  파일의 내용에서 나타나는 문자들에 대해 자주 나타나는 문자들을 아래와 같이 순서대로 출력하세요.
- \[ \] -> [177]회 나타남
- [e] -> [97]회 나타남
- [t] -> [85]회 나타남


In [30]:
def text_contents(filename):
    with open(filename, 'r') as f:
        contents=f.read()
        fa={}
        for text in contents:
            if text in fa:
                fa[text]+=1F
            else:
                fa[text]=1
        return fa

dictionary=text_contents('dataset/mydata.txt').items()
dictionary=sorted(dictionary, key=lambda x: x[1], reverse=True)
dictionary

for k,v in dictionary:
    if k=='\n':
        pass
    else:
        print(f'[{k}] -> {v}개')

[ ] -> 177개
[e] -> 97개
[t] -> 85개
[a] -> 78개
[o] -> 73개
[n] -> 60개
[s] -> 60개
[r] -> 54개
[i] -> 50개
[h] -> 48개
[l] -> 34개
[u] -> 27개
[d] -> 24개
[c] -> 23개
[w] -> 20개
[m] -> 20개
[f] -> 17개
[y] -> 15개
[p] -> 15개
[b] -> 13개
[g] -> 11개
[v] -> 9개
['] -> 8개
[k] -> 7개
[!] -> 2개


## 07/18

#### Q7. 두 개의 수를 입력한 후 두 개의 수에 대한 사칙연산을 수행하세요. (0을 입력한 경우 다시 입력하도록 조치)

In [1]:
# Cal4 클래스 만들어서 작성

class Cal4():
    def __init__(self, num1, num2):
        self.num1=num1
        self.num2=num2
        
    def add(self):
        return self.num1+self.num2
    
    def sub(self):
        return self.num1+self.num2
    
    def div(self):
        return self.num1/self.num2
    
    def mul(self):
        return self.num1*self.num2
    
while True:
    digits=input('>> 사칙연산을 수행할 숫자 두 개를 입력하세요\nex) 4,5\n')
    
    if digits[0]=='0' or digits[1]==0:
        print('>> 경고!!!!!! 0이 아닌 숫자를 두 개를 입력해주세요!!!')
        continue
        
    else:
        digit=digits.split(',')
        c=Cal4(int(digit[0]),int(digit[1]))
        
        print('*'*50)
        print('''
        1. 덧셈
        2. 뺄셈
        3. 나눗셈
        4. 곱셈
        ''')
        print('*'*50)
        
        cal=input('>> 수행하고 싶은 사칙연산을 고르세요.\n')
        if cal=='1':
            print(c.add())
        elif cal=='2':
            print(c.sub())
        elif cal=='3':
            print(c.div())
        elif cal=='4':
            print(c.mul())
        break

>> 사칙연산을 수행할 숫자 두 개를 입력하세요
ex) 4,5
4,5
**************************************************

        1. 덧셈
        2. 뺄셈
        3. 나눗셈
        4. 곱셈
        
**************************************************
>> 수행하고 싶은 사칙연산을 고르세요.
2
9


#### Q8. Order 클래스를 상속받아 extraOrder 클래스에서 메서드 오버라이딩하여 출력가격에 원이 추가되도록 출력하세요.

In [4]:
class Order: 
    def __init__(self, name): 
        self.customer = 0 
        self.name = name 
        
    def order(self, price): 
        self.customer += price 
        return self.customer

order=Order('kevin')
print(order.order(1000))


class ExtraOrder(Order):
    def __init__(self,name):
        super().__init__(self)
        
    def order(self, price):   
        super().order(price)
#         self.customer += price 
        return f'{self.customer}원'        

1000


In [5]:
order=ExtraOrder('kevin')
order.order(1000)

'1000원'

#### Q9. 업무미팅이 2시임을 알려주는 자동 이메일 클래스 AutoEmail을 작성하여 아래와 같이 출력하세요.
-안녕하세요. Kevin님, 업무미팅은 2시입니다.


In [86]:
import time
from datetime import datetime 

while True:
    time.sleep(1)
    now_time=datetime.now()
    now_hours=now_time.hour
    now_minutes=now_time.minute
    if (now_hours==13) & (now_minutes==50):
        print('안녕하세요. Kevin님, 업무미팅은 2시입니다.')
        break

안녕하세요. Kevin님, 업무미팅은 2시입니다.


In [12]:
import time
from datetime import datetime 

class AutoEmail:
    def __init__(self,task,name,time):
        self.task=task
        self.name=name
        self.time=time
    def alarm(self):
        if datetime.now().hour==self.time:
            print(f'{self.name}님, 업무미팅이 진행중입니다.')
        else:
            print(f'{self.name}님, {self.time}시에 {self.task}이 존재합니다.')

In [13]:
a=AutoEmail('점심약속','애림',13)
a.alarm()

애림님, 13시에 점심약속이 존재합니다.


## 07/19

#### Q10. 정규표현식을 사용하여 text에서 전화번호만 출력하세요.

text="문의사항이 있으면 032-232-3245로 연락주시기 바랍니다."

In [19]:
import re

text="문의사항이 있으면 032-232-3245로 연락주시기 바랍니다."

In [20]:
#search활용

p=re.compile('\d+[-]\d+[-]\d+')
p.search(text).group()

'032-232-3245'

In [26]:
#finditer 활용

p=re.compile('\d+[-]\d+[-]\d+')
for i in p.finditer(text):
    print(i.group())

032-232-3245


In [32]:
#findall 활용
p=re.compile('\d+[-]\d+[-]\d+')
p.findall(text)

['032-232-3245']

#### Q11. 정규표현식을 사용하여 text 에서 에러가 들어간 부분만 포함하는 리스트 출력하세요.

text="에러 1122, 레퍼런스 오류, 에러 1033, 아규먼트 오류, 에러 xxx"

In [17]:
import re

text="에러 1122, 레퍼런스 오류, 에러 1033, 아규먼트 오류, 에러 xxx"

p=re.compile('[에러][\s\w]+')
p.findall(text)

['에러 1122', '에러 1033', '에러 xxx']

#### Q12. 정규표현식을 사용하여 text 에서 지역코드만 출력하세요

text="문의사항이 있으면 032-232-3245로 연락주시기 바랍니다."

In [34]:
import re

text="문의사항이 있으면 032-232-3245로 연락주시기 바랍니다."

In [39]:
#search 활용

p=re.compile('\d+')
p.search(text).group()

'032'

In [55]:
#finditer 활용

p=re.compile('\d+')

li=[]
for i in p.finditer(text):
    li.append(i.group())
print(li[0])
   

032


In [56]:
#findall 활용

p=re.compile('\d+')
p.findall(text)[0]

'032'

#### Q13. 정규표현식을 사용하여 text 에서 지역코드를 제외한 번호만 출력하세요

text="문의사항이 있으면 032-232-3245로 연락주시기 바랍니다."

In [124]:
text="문의사항이 있으면 032-232-3245로 연락주시기 바랍니다."

In [131]:
#findall 활용

p=re.compile('-([\d]+)')
p.findall(text)

['232', '3245']

#### Q14. 'abcdefghij'에 대해 중첩을 적용한 서브그룹 5개로 컴파일하여 group()함수를 이용하여 'abcdefghi'와 e를 출력하세요.

In [112]:
text='abcdefghij'
p=re.compile('(\w(\w(\w(\w(\w)\w)\w)\w)\w)')

In [66]:
#search 활용

s=p.search(text)
s.group(1), s.group(5)

('abcdefghi', 'e')

In [68]:
#match 활용

m=p.match(text)
m.group(1),m.group(5)

('abcdefghi', 'e')

In [82]:
#findall 활용

f=p.findall(text)
f[0][0],f[0][4]

('abcdefghi', 'e')

#### Q15. 위 문제에서 모든 서브 그룹에 대한 문자열을 포함하는 튜플을 출력하세요.

In [ ]:
text='abcdefghij'
p=re.compile('(\w(\w(\w(\w(\w)\w)\w)\w)\w)')

In [100]:
#findall 활용

f=p.findall(text)
f[0]

('abcdefghi', 'bcdefgh', 'cdefg', 'def', 'e')

#### Q16. 이름으로 그룹을 참조하여 'Lots of punctuation'에서 Lots를 출력하세요.

In [7]:
import re

text='Lots of punctuation'

p=re.compile('(?P<그룹>\w+)\s\w+\s(?P<그룹2>\w+)')
p.search(text).group('그룹')

'Lots'

#### Q17. 'Paris is very very beautiful'에서 'very very'를 출력하기

In [14]:
import re

text='Paris is very very beautiful'

p=re.compile('\w+\s\w+')
p.findall(text)[1]

'very very'

#### Q18. 정규 표현식을 작성하여 아래와 같이 출력하세요.
'1 apple', '5 oranges', '3 boys', '4 girls', '10 army', '11 mr'

In [8]:
text='1 apple,5 oranges,3 boys,4 girls;10 army|11 mr'

In [9]:
#findall 활용

p=re.compile('\d \w+')
p.findall(text)

['1 apple', '5 oranges', '3 boys', '4 girls', '0 army', '1 mr']

#### Q19. text에서 'H,h'만 출력하세요.

In [10]:
import re

text='Hello my friend! Life is too short'

p=re.compile('[Hh]')
p.findall(text)

['H', 'h']

#### Q20. text에서 'H,h'만 빼고 출력하세요.

In [11]:
import re

text='Hello my friend! Life is too short'

p=re.compile('[^Hh]')
p.findall(text)

['e',
 'l',
 'l',
 'o',
 ' ',
 'm',
 'y',
 ' ',
 'f',
 'r',
 'i',
 'e',
 'n',
 'd',
 '!',
 ' ',
 'L',
 'i',
 'f',
 'e',
 ' ',
 'i',
 's',
 ' ',
 't',
 'o',
 'o',
 ' ',
 's',
 'o',
 'r',
 't']

# 7/21

#### Q21.  'we are going home'에서 home만 출력하세요.

In [16]:
import re

text='we are going home'

p=re.compile('\w+')
p.findall(text)[-1]

'home'

In [1]:
import re

text='we are going home'

p=re.compile('\w+$')
p.findall(text)

['home']

#### Q22. '199305, 1923A, a93247'에서 '199305'만 출력하세요.

In [28]:
import re

text='199305, 1923A, a93247'

p=re.compile('(\w+)')
p.findall(text)[0]

'199305'

In [2]:
import re

text='199305, 1923A, a93247'

p=re.compile('^\w+')
p.findall(text)

['199305']

#### Q23. '12345abc'에서 'abc'만 출력하세요.

In [29]:
import re

text= '12345abc'
p=re.compile('[a-z]+')
p.search(text).group()

'abc'

#### Q24. 'abc12345Abc'에서 'a'만 출력하세요.


In [30]:
import re

text='abc12345Abc'

p=re.compile('\w')
p.findall(text)[0]

'a'

In [7]:
#숫자가 아닌 것은 공백으로 대체하기

import re

text='12345abc'

re.sub('[^0-9]','',text)

'12345'

#### Q25. 'abc12345Abc'에서 'A'만 출력하세요.

In [31]:
import re

text='abc12345Abc'

p=re.compile('[A-Z]')
p.search(text).group()

'A'

# 7/22

#### Q26. 'Banker'에서 'anker', 'banker123'에서 'banker'를 출력하세요

In [2]:
import re
text='Banker'
text2='banker123'
'''
'anker'
'banker'
'''

"\n'anker'\n'banker'\n"

In [10]:
re.sub('B','',text)

'anker'

In [14]:
re.sub('\d','',text2)

'banker'

#### Q27. 'KOREA 대한민국'에서 '대'만 출력하세요.

In [16]:
import re

text='KOREA 대한민국'

re.search('[가-힣]',text).group()

'대'

#### Q28. 'aaaaBBBcccDDDeee'을 모두 출력하세요.
text = 'aaaBBccDDeeaaaaBBBcccDDDeeeeeeDDDcccBBBaaaa'


In [19]:
import re

text = 'aaaBBccDDeeaaaaBBBcccDDDeeeeeeDDDcccBBBaaaa'

re.search('a{4}B{3}c{3}D{3}e{3}',text).group()

'aaaaBBBcccDDDeee'

#### Q29. 아래의 경우에서 \<html>만 출력하세요

pattern = re.compile('<.*>')

print(len(text)) p = pattern.search(text) p.group()

In [20]:
'''
text = "<html><head><title>Title</title></head><body></body></html>'
'''

'\ntext = "<html><head><title>Title</title></head><body></body></html>\'\n'

In [27]:
text = '<html><head><title>Title</title></head><body></body></html>'

pattern = re.compile('<.*>')      # greedy 방식: '.*'
print(len(text)) 
p = pattern.search(text)
p.group()[:6]

59


'<html>'

In [3]:
text = '<html><head><title>Title</title></head><body></body></html>'

pattern = re.compile('<.*?>')     # non-greedy 방식: '.*?'
print(len(text)) 
p = pattern.search(text)
p.group()[:6]

59


'<html>'

#### Q30. '1234a1234'에서  '1', '2', '3', '4'를 모두 출력하세요.

In [21]:
import re

text='1234a1234'

re.findall('\d',text)

['1', '2', '3', '4', '1', '2', '3', '4']

# 07/25

#### Q32. text에서 전체문장 모두 출력하세요.

```
text = "what are you doing?\nit is going to be late for school\nwe need to hurry up"
regex = re.compile('.*')
mo = regex.search(text)
print(mo.group())

```

In [1]:
import re

text = "what are you doing?\nit is going to be late for school\nwe need to hurry up"

In [2]:
#방법2
                                      #'.*': 줄바꿈 문자 전까지만 해당
regex = re.compile('.*',re.DOTALL)    #re.DOTALL: dot(.)이 줄바꿈 문자도 포함해서 매치함
mo = regex.search(text)

print(mo.group())

what are you doing?
it is going to be late for school
we need to hurry up


In [ ]:
#방법1

regex = re.compile('(.|\n)*')    #greedy 방식(줄바꿈 포함)
mo = regex.search(text)

print(mo.group())

#### Q33.  text에서 대소문자 구분없이 전체문장을 한 단어씩 모두 출력하세요

In [6]:
import re

text = 'Friend fRiend friEnd FRIEND'

- 모든단어 추출

In [30]:
print(re.search('[\s\w]+',text).group())

Friend fRiend friEnd FRIEND


In [31]:
print(re.search('.*',text).group())

Friend fRiend friEnd FRIEND


In [32]:
print(re.match('[\s\w]+',text).group())

Friend fRiend friEnd FRIEND


- 한 단어씩 추출

In [12]:
p=re.compile('friend*',re.I)

for t in re.findall(p,text):
    print(t)

Friend
fRiend
friEnd
FRIEND


- 한 글자씩 추출

In [34]:
#방법1

words=re.findall('[\w]',text)

for w in words:
    print(w,end=" ")

F r i e n d f R i e n d f r i E n d F R I E N D 

In [9]:
#방법2

p=re.compile('[a-z]',re.IGNORECASE)

for i in re.findall(p,text):
    print(i,end=' ')

F r i e n d f R i e n d f r i E n d F R I E N D 

#### Q34. 1609160537.371015을 "Sat Jun 26 08:35:03 2021" 포멧으로 출력하세요.

In [14]:
time=1609160537.371015

In [16]:
#방법1

from datetime import datetime 

date=datetime.fromtimestamp(time)
date.strftime('%c')

'Mon Dec 28 22:02:17 2020'

In [18]:
#방법2
import time

timestring=time.ctime(1609160537.371015)
timestring

'Mon Dec 28 22:02:17 2020'

- ctime() 함수는 주어진 timestamp를 현지 시간대 기준으로 소위 미국에서 흔히 사용되는 요 월 일 시:분:초 년 포멧으로 변환해줍니다. 그냥 간단하게 timestamp가 나타내는 날짜와 시간을 확인해보는 용도로 쓰기에 좋습니다.


In [20]:
#방법3

from datetime import datetime

time = datetime.fromtimestamp(1609160537.371015)
time = time.strftime("%a %b %d %H:%S:%S %Y")
time

'Mon Dec 28 22:17:17 2020'

#### Q35.  현재 날짜와 시간을 "Sat Jun 26 08:35:03 2021" 포멧으로 출력하세요.


In [44]:
now=datetime.now()

now.strftime('%c')    #Local version의 날짜와 시간

'Mon Jul 25 20:43:26 2022'

# 07/26

#### Q36. 현재 시간을 년-월-일 시:분:초로 출력하세요.

In [31]:
from datetime import datetime 

now = datetime.now()

print(now.strftime('%Y-%m-%d %H:%M:%S'))

2022-07-26 17:38:39


#### Q37. 현재 시간을 time.time을 불러와서 년-월-일 시:분:초로 출력하세요.


In [35]:
import time 
from datetime import datetime 

now = time.time()
now_datetime = datetime.fromtimestamp(now)

print(now_datetime.strftime('%Y-%m-%d %H:%M:%S'))

2022-07-26 17:40:53


#### Q38. 올해 경과된 날짜수 계산하세요


In [64]:
from datetime import datetime 

startday = datetime.strptime('2022-01-01','%Y-%m-%d')
now = datetime.now()

days = now - startday

print(f'올해 경과된 날짜수는 {days.days}일 입니다.')

올해 경과된 날짜수는 206일 입니다.


#### Q39. 현재 요일을 "2021-6-26 오늘은 토요일입니다."와 같은 형식으로 출력하세요.


In [119]:
now=datetime.now()

In [120]:
def get_yoil(x):
    n = x.weekday()
    
    date = x.strftime('%Y-%m-%d')
    yoil = ['월요일','화요일','수요일','목요일','금요일','토요일','일요일']
    
    return date, yoil[n]

In [122]:
print(f'{get_yoil(now)[0]} 오늘은 {get_yoil(now)[1]}입니다.')

2022-07-26 오늘은 화요일입니다.


#### Q40. 1에서 백만까지 더하는데 걸리는 프로그램 실행 시간을 밀리초(ms) 단위로 구하세요.

In [1]:
import time 
from datetime import datetime 

n=0

start_time = datetime.now()

for i in range(1000000):
    n += 1
    
end_time = datetime.now()

print(f'{(end_time - start_time).microseconds} 밀리초(ms)')

98789 밀리초(ms)


In [2]:
import time 
from datetime import datetime 

n=0

start_time = datetime.now()

sum(range(1,1000001))
    
end_time = datetime.now()

print(f'{(end_time - start_time).microseconds} 밀리초(ms)')

34861 밀리초(ms)


# 07/27

#### Q41. 아래 코드를 보완하여 발생 가능한 모든 예외(정수, 인덱스, 미리 파악하지 못한 예외)를 처리한 후 마지막에  '모든 예외처리 완료'를 출력하세요.
- list_num = [52,273,32,72,100]

- num_input = int(input('정수 입력> '))
- print(f'{num_input}번째 요소: {list_num[num_input-1]}')

In [13]:
# IndexError: list index out of range
# ValueError: invalid literal for int() with base 10: '2.3'
# ValueError: invalid literal for int() with base 10: '정수'

while True:
    try:
        list_num = [52,273,32,72,100]
        num_input = int(input('정수 입력> '))
        print(f'{num_input}번째 요소: {list_num[num_input-1]}')  

    except:
        if (IndexError):
            print('※ 경고: 정수만 입력해주세요')
            continue
            
        if (ValueError):
            print('※ 경고: -4 ~ 5 사이의 숫자만 입력해주세요.')
            continue

    finally:
        if num_input>=-4 & num_input<=5:
            print('모든 예외처리 완료')
            break
    


정수 입력> 9
※ 경고: 정수만 입력해주세요
정수 입력> 45
※ 경고: 정수만 입력해주세요
정수 입력> 2
2번째 요소: 273
모든 예외처리 완료


#### Q42. 기본가격 1000원인 2개의 상품에 대하여 임의의 추가 가격을 입력시 가격 조정한 결과를 반환하는 Price 클래스를 생성 후 객체를 만들어 price1, price2를 수행하세요. 
- price1 : 기본가격 + 추가가격
- price2 : (기본가격 + 추가가격) * 90%


In [55]:
#방법1

class Price:
    def __init__(self):
        self.price1 = 1000      
        self.price2 = 1000      
        
    def add(self, n, add):
        self.add = add
        self.n = n
        
        if self.n == 1:
            self.price1 += self.add
            return f'price1의 기본 가격이 "{self.price1}원"으로 변경되었습니다.'
        elif self.n == 2:
            self.price2 += self.add
            self.price2 *= 0.9
            self.price2 = int(self.price2)
            return f'price2의 기본 가격이 "{self.price2}원"으로 변경되었습니다.'
    


In [56]:
price = Price()
price.add(1,300)

'price1의 기본 가격이 "1300원"으로 변경되었습니다.'

In [57]:
price = Price()
price.add(2,1000)

'price2의 기본 가격이 "1800원"으로 변경되었습니다.'

In [70]:
#방법2

class Price:
    def __init__(self):
        self.price1 = 1000      
        self.price2 = 1000      
        
    def price1_add(self, add):
        self.add = add
        self.price1 += self.add
        return f'price1의 기본 가격이 "{str(self.price1)}원"으로 변경되었습니다.'
    
    def price2_add(self, add):
        self.add = add    
        self.price2 = int((self.price2 + self.add)*0.9)
        return f'price2의 기본 가격이 "{str(self.price2)}원"으로 변경되었습니다.'
    

In [73]:
price = Price()
price.price1_add(500)

'price1의 기본 가격이 "1500원"으로 변경되었습니다.'

In [74]:
price.price2_add(2000)

'price2의 기본 가격이 "2700원"으로 변경되었습니다.'

#### Q43. strings를 문자의 크기 순서로 내림차순 정렬하세요
- strings = ['a', 'ca', 'bar', 'aaaa', 'ababa']


In [2]:
strings = ['a', 'ca', 'bar', 'aaaa', 'ababa']

In [8]:
#방법1

strings.sort(key = lambda x: len(x), reverse=True)
strings

['ababa', 'aaaa', 'bar', 'ca', 'a']

In [9]:
#방법2

strings.sort(key = len)
strings.reverse()
print(strings)

['ababa', 'aaaa', 'bar', 'ca', 'a']


In [10]:
#방법3

strings.sort(key = len, reverse=True)
strings

['ababa', 'aaaa', 'bar', 'ca', 'a']

#### Q44. strings를 다양한 문자가 포함된 순서로 정렬하세요

- strings = ['foo', 'card', 'bar', 'aaaa', 'abab']
- strings.sort(key = lambda x:len(set(x)))
- strings


In [21]:
strings = ['foo', 'card', 'bar', 'aaaa', 'abab']

strings.sort(key = lambda x:len(set(x)), reverse=True)
strings

['card', 'bar', 'foo', 'abab', 'aaaa']

#### Q45. 'abcde' 를 'edcba'로 바꾸어 출력하세요.(5가지 방법)


In [12]:
word='abcde'

In [13]:
#방법1

word[4]+word[3]+word[2]+word[1]+word[0]

'edcba'

In [14]:
#방법2

word[-1]+word[-2]+word[-3]+word[-4]+word[-5]

'edcba'

In [15]:
#방법3

word[-1::-1]

'edcba'

In [16]:
#방법4

word[5::-1]

'edcba'

In [17]:
#방법5

''.join(sorted(word, reverse=True))

'edcba'

# 07/28

#### Q46. numbers 내부에 들어 있는 숫자가 몇 번 등장하는지를 출력하는 코드를 작성하세요.
numbers = [3,6,3,5,8,2,9,7,4,3,6,3,5,8,2,9,7,4]


In [29]:
numbers = [3,6,3,5,8,2,9,7,4,3,6,3,5,8,2,9,7,4]

In [34]:
def numbering(x):
    set_x = sorted(list(set(x)))
    
    for i in set_x:
        print(f'입력하신 리스트에 "{i}"가 {x.count(i)}개 존재합니다.')

In [35]:
numbering(numbers)

입력하신 리스트에 "2"가 2개 존재합니다.
입력하신 리스트에 "3"가 4개 존재합니다.
입력하신 리스트에 "4"가 2개 존재합니다.
입력하신 리스트에 "5"가 2개 존재합니다.
입력하신 리스트에 "6"가 2개 존재합니다.
입력하신 리스트에 "7"가 2개 존재합니다.
입력하신 리스트에 "8"가 2개 존재합니다.
입력하신 리스트에 "9"가 2개 존재합니다.


#### Q47. 코딩을 한줄로 작성해서 동일한 결과를 출력하세요

In [ ]:
list = []
for i in range(0,20,2):
    list.append(i*i)
print(list())

In [36]:
print([i for i in range(0,20,2)])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


#### Q48. 반복문으로 팩토리얼을 구하는 사용자 함수를 작성하고 5!, 10!를 구하세요.

In [43]:
def factorial_1(n):
    y=1
    for i in range(1,n+1):
        y *= i
    return y

In [44]:
factorial_1(5) 

120

In [46]:
factorial_1(10)

3628800

#### Q49. 재귀란 '자기자신을 호출하는 것'을 의미한다. 재귀함수를 이용해서 팩토리얼을 구하는 사용자 함수를 작성하고 1!, 5!, 10!를 구하세요.
factorial(n) = n * factorial(n-1) (n >= 1)


In [47]:
def factorial_2(n):
    if n == 1:
        return 1
    return factorial(n-1)*n

In [48]:
factorial_2(1)

1

In [49]:
factorial(5)

120

In [50]:
factorial(10)

3628800

#### Q50. list a의 모든 원소를 실수형으로 바꾸어 출력하세요
a = [1,2,3,4,5]

In [1]:
a = [1,2,3,4,5]

In [2]:
float_a = [ float(i) for i in a ]
float_a

[1.0, 2.0, 3.0, 4.0, 5.0]

In [3]:
for i, j in enumerate(a):
    a[i] = float(j)
a

[1.0, 2.0, 3.0, 4.0, 5.0]

In [4]:
list(map(lambda x: float(x),a))

[1.0, 2.0, 3.0, 4.0, 5.0]

# 07/29

#### Q.31 [도전과제] 문자열 리스트 states를 정형화하여 아래와 같이 출력하세요.


In [18]:
states = ['   Alabama ', 'Georgia!', 'Georgia', 'georgia', 'FlOrIda',
          'south   carolina##', 'West virginia?']
'''
[출력]
['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']
'''

"\n[출력]\n['Alabama',\n 'Georgia',\n 'Georgia',\n 'Georgia',\n 'Florida',\n 'South   Carolina',\n 'West Virginia']\n "

In [39]:
import re
def cleaning(x):
    cleaned_data = []
    for i in x:
        i = re.search('[a-zA-Z\s]+',i).group()        # 문자, 공백으로 이루어진 부분 찾기
        i = i.strip()                             # 양 옆 공백 제거
        i = i.lower().title()                     # 소문자화-> 단어 첫글자만 대문자화
        cleaned_data.append(i)
    return cleaned_data

In [40]:
cleaning(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

#### Q51. 게시물의 총 건수와 한 페이지에 보여 줄 게시물 수를 입력시 총 페이지 수를 출력하는 프로그램

인자:게시물의 총 건수,한 페이지에 보여 줄 게시물 수

In [61]:
def page_num(all_n, one_n):
    return all_n // one_n +1

In [69]:
x =input('>> 원하시는 게시물의 총 건수와 한 페이지에 보여줄 게시물 수를 출력해주세요.\nex)10,4\n')

all_n = int(x.split(',')[0])
one_n = int(x.split(',')[1])

p = page_num(all_n, one_n)
print('\n총 페이지 수: '+str(p)+'p')

>> 원하시는 게시물의 총 건수와 한 페이지에 보여줄 게시물 수를 출력해주세요.
ex)10,4
28,9

총 페이지 수: 4p


#### Q52. 랜덤하게 1000명의 이름, 키와 몸무게 만들어 저장한 후 다시 불러내어 다음과 같이 출력하세요.

- 이름 :라바
- 몸무게: 80
- 키: 146
- BMI: 37.53049352598987
- 결과: 과체중


In [59]:
import random
import numpy as np
import pandas as pd

word = '김이박최정윤황'
word2 = '가나다라마바사아자차카타파하개내대래매배새애재채캐태패해기니디리미비시이지치키티피히구누두루무부수우주추쿠투푸후'

#이름 랜덤 생성
name = []
for w in range(1000):
    last_name = random.choice([i for i in word])
    first_name = random.sample([i for i in word2],2)
    full_name = last_name + ''.join(first_name)
    name.append(full_name)
    
#몸무게 랜덤 생성
weight = np.random.randint(40, 120, size = 1000)

#키 랜덤 생성
height = np.random.randint(140, 190, size = 1000)

#기본 정보로 데이터프레임 생성
df = pd.DataFrame(columns = ['Name','Weight','Height'])
df['Name'] = name
df['Weight'] = weight
df['Height'] = height

#BMI 컬럼 생성
df['BMI'] = round(df['Weight']/(df['Height']/100*df['Height']/100),2)

#비만도 컬럼 생성
result = []
for i in df['BMI']:
    if i <= 18.5:
        res = '저체중'
    elif i < 23:
        res = '정상'
    elif i < 25:
        res = '과체중'
    else:
        res = '비만'
    result.append(res)
df['Result'] = result

df.head(10)

Name  Weight  Height    BMI Result
0  정이매      77     187  22.02     정상
1  박투히      67     162  25.53     비만
2  이아사      70     189  19.60     정상
3  최자구      50     162  19.05     정상
4  윤다기      57     165  20.94     정상
5  이부라      94     152  40.69     비만
6  황아매      68     157  27.59     비만
7  최후채      65     161  25.08     비만
8  이바지      57     149  25.67     비만
9  김리차      47     142  23.31    과체중

# 08/01

#### Q53.입력한 숫자를 천 단위로 구분하여 출력하세요

In [1]:
def thousand(n):
    return f'{n:,}'

In [2]:
thousand(4512145878)

'4,512,145,878'

#### Q54. 카운터에서 거스름돈으로 사용할 500원,100원,50원,10원짜리 동전이 무한히 존재한다고 가정한다. 손님에게 거슬러 줘야할 돈이 N원일 때, 거슬러 줘야할 동전의 최소 개수를 구하세요. 단, 거슬러 줘야할 돈 N원은 항상 10의 배수이다. N은 2750원이다.

In [8]:
#방법1

def change(price):
    c1 = price//500
    c2 = (price - 500*c1) // 100
    c3 = (price - 500*c1 - 100*c2) //50
    c4 = (price - 500*c1 - 100*c2 - 50*c3)//10
    print('*****거스름돈*****\n- 500원: '+str(c1)+'개\n- 100원: '+str(c2)+'개\n-  50원: '+str(c3)+'개\n-  10원: '+str(c4)+'개')

In [15]:
change(5360)

*****거스름돈*****
- 500원: 10개
- 100원: 3개
-  50원: 1개
-  10원: 1개


In [7]:
#방법2

def change(n):
    n500, n100 = divmod(n,500)
    n100, n50 = divmod(n100,100)
    n50, n10 = divmod(n50,50)
    n10, n = divmod(n10,10)
    
    print('*****거스름돈*****\n- 500원: '+str(n500)+'개\n- 100원: '+str(n100)+'개\n-  50원: '+str(n50)+'개\n-  10원: '+str(n10)+'개')


In [6]:
change(5360)

*****거스름돈*****
- 500원: 10개
- 100원: 3개
-  50원: 1개
-  10원: 1개


In [11]:
#방법3

n = 2750
count = 0

# 큰 단위의 화폐부터 차례대로 확인하기
coin_types = [500, 100, 50, 10]

for coin in coin_types:
    count += n // coin # 해당 화폐로 거슬러 줄 수 있는 동전의 개수 세기
    n %= coin

print(count)

8


# 08/02

#### Q55. dataset/mydata.txt 파일에 있는 단어 개수를 출력하세요.

In [55]:
import re

with open('dataset/mydata.txt','r') as fr:
    mydata = fr.readlines()
    mydata = ' '.join(mydata)
    mydata = re.sub('\s{1,}',' ',mydata)
    mydata_list = re.findall('[\w\']+', mydata)
# print(mydata_list)
print('총 단어의 개수: '+ str(len([i for i in mydata_list])) + '개')

총 단어의 개수: 213개


In [5]:
import re
with open('dataset/mydata.txt','r') as fr:
    mydata = fr.read()
    mydata = re.sub('\s{1,}',' ',mydata)
    mydata_list = re.findall('[\w\']+', mydata)
print('총 단어의 개수: '+ str(len([i for i in mydata_list])) + '개')

총 단어의 개수: 213개


In [9]:
with open('dataset/mydata.txt','r') as fr:
    mydata = fr.read()
    mydata = re.sub('\s{1,}',' ',mydata)
    mydata_list = re.findall('[\w\']+', mydata)
    mydata_word = []
    for i in mydata_list:
        try:
            if len(re.search('[\'](\w+)',i).group(1)) > 0:
                print(i)
                if i[-1] == 't':
                    if i == "won't":
                        mydata_word.append('will','not')
                    elif i == "don't":
                        mydat_word.append('do','not')
                else:
                    mydata_word.append(i.split("'")[0])
                    if i.split("'")[1] == 've':
                        mydata_word.append('have')
                    elif i.split("'")[1] == 's':
                        mydata_word.append('is')
                    elif i.split("'")[1]  == 're':
                        mydata_word.append('are')
        except:
            mydata_word.append(i)
# print(mydata_word)
print('총 단어의 개수: '+ str(len(mydata_word)) + '개')

we've
there's
won't
don't
you're
it's
it's
it's
총 단어의 개수: 219개


#### Q56. 파일이름과 특정 단어를인자로 입력하면 그 파일에 있는 특정 단어의 개수를 반환하는 사용자 함수를 이용하여 mydata 파일에서 how의 개수를 출력하세요.


In [52]:
def word_count(word):
    with open('dataset/mydata.txt','r') as fr:
        mydata = fr.readlines()
        mydata = ' '.join(mydata)
        mydata = re.sub('\s{1,}',' ',mydata)
        mydata_list = re.findall('[\w\']+', mydata)
        cnt = mydata_list.count(word)
        
    print(f'단어 "{word}"의 개수: {cnt}개')
    
    

In [53]:
word_count('how')

단어 "how"의 개수: 2개


In [15]:
def word_count(filename ,word):
    with open('dataset/'+filename,'r') as fr:
        mydata = fr.read()
        mydata = re.sub('\s{1,}',' ',mydata)
        mydata_list = re.findall('[\w\']+', mydata)
        
    mydata_word = []
    for i in mydata_list:
        try:
            if len(re.search('[\'](\w+)',i).group(1)) >= 1:
#                 print(i)
                if i[-1] == 't':
                    if i == "won't":
                        mydata_word.append('will','not')
                    elif i == "don't":
                        mydat_word.append('do','not')
                else:
                    mydata_word.append(i.split("'")[0])
                    if i.split("'")[1] == 've':
                        mydata_word.append('have')
                    elif i.split("'")[1] == 's':
                        mydata_word.append('is')
                    elif i.split("'")[1]  == 're':
                        mydata_word.append('are')
        except:
            mydata_word.append(i)
            
    cnt = mydata_word.count(word)

    print(f'단어 "{word}"의 개수: {cnt}개')

In [16]:
word_count('mydata.txt','how')

단어 "how"의 개수: 2개


In [19]:
def countWord(filename, word):
    word = word.lower()
    with open(filename, 'r') as f:
        text = f.read()
        text = text.lower()
        pos = text.find(word)
        count = 0
        while pos != -1:
            count += 1
            pos = text.find(word, pos+1)
    return count

# 08/03

#### Q57. 문자열을 입력받아 같은 문자가 연속적으로 반복되는 경우에 그 반복 횟수를 표시해 문자열을 압축하여 표시하세요.
- 예) "aaabbcccccca" -> a3b2c6a1

In [25]:
#전체 문자에 대해서

word = input('>>문자를 입력하세요 ')
word_set = set(word)

w_c = ''
if len(word_set) > 1:
    for i in word_set:
        word_name = i
        word_cnt = str(word.count(i))
        w_c += (word_name + word_cnt)
print(w_c)

>>문자를 입력하세요 aasnafsdddd
a3d4n1s2f1


In [1]:
#방법1

word = input('<<문자를 입력하세요.\n')
word_cnt =''

for i in range(len(word)):
    if i == 0:
        word_cnt = word[i]
        cnt = 1
    elif word_cnt[-1] == word[i]:
        cnt += 1
    elif word_cnt[-1] != word[i]:
        word_cnt += str(cnt) + word[i]
        cnt = 1
    if i == len(word)-1:
        word_cnt += str(cnt)
        
print(word_cnt)

<<문자를 입력하세요.
aaabbcccccca
a3b2c6a1


In [ ]:
#방법2

word = input('>>문자를 입력하세요.\n')

w = word[0]


In [8]:
#방법3

from itertools import groupby

t = 'aaaabbbccccdda'

print("".join(f'{x}{list(y)}' for x, y in  groupby(t)))

print("".join(f'{x}{len(list(y))}' for x, y in  groupby(t)))


a['a', 'a', 'a', 'a']b['b', 'b', 'b']c['c', 'c', 'c', 'c']d['d', 'd']a['a']
a4b3c4d2a1


# 08/04

#### Q58. N개의 요소로 이루어진 배열이 있을 때 주어진 수들을 M번 더하여 가장 큰 수를 만드는 프로그램을 작성하세요. 단 배열의 특정한 인덱스(번호)에 해당하는 수가 K번을 초과하여 더해질 수 없는 것이 특징이다.
프로그램은 다음 조건을 만족하는 N, M, K를 공백으로 일차 입력하고 N개의 배열을 공백으로 이차 입력하면 결과물을 출력하는 방식으로 수행함.
- 2 <= N <= 1000
- 1 <= M <= 10000
- 1 <= K <= 10000


1. input('배열 요소로 이루어진 개수' '가장 큰 수가 되게 요소들을 총 M번 더하도록 함' '대신 한 요소당 k번이 최대로 더할 수 있음' )
2. input(배열 요소 입력)
3. 제일 큰 수를 더할 수 있는 제한이 k번

In [41]:
#함수 지정: for문, if문 포함
def array_max(n,m,k, arr):
    total = 0
    while True:
        for i in range(k):
            arr_max = arr.max()    #제일 큰 수를 찾아서 k번 더하기
            total += arr_max       
        idx = np.where(arr==arr_max)  #제일 큰 수의 배열 속 인덱스 찾기
        arr = np.delete(arr,idx)      #제일 큰 수 삭제
        m -= k                #남아있는 덧셈 횟수 조정
    
        if m < k:             #남아있는 덧셈 횟수가 최대 덧셈횟수보다 작은 경우
            for i in range(m):
                arr_max = arr.max()
                total += arr_max     #제일 큰 수를 남아있는 횟수 만큼 더하기
            break                  #그럼 끝
    return f'요소당 최대 덧셈 횟수가 {k}번, 총 덧셈 횟수가 {m}번 일 때, 주어진 배열을 가지고 만들 수 있는 최대값은 {total}입니다.'

In [30]:
#함수 지정: for문, if문 포함2
def array_max(n,m,k, arr):
    total = 0
    x,y = divmod(m,k)
    for i in range(x):
        arr_max = arr.max()    #제일 큰 수를 찾아서 k번 더하기
        total += arr_max*k       
        idx = np.where(arr==arr_max)  #제일 큰 수의 배열 속 인덱스 찾기
        arr = np.delete(arr,idx)      #제일 큰 수 삭제
        
        if i == x-1: 
            arr_max = arr.max()
            total += arr_max*y    #제일 큰 수를 남아있는 횟수 만큼 더하기

    return f'요소당 최대 덧셈 횟수가 {k}번, 총 덧셈 횟수가 {m}번 일 때, 주어진 배열을 가지고 만들 수 있는 최대값은 {total}입니다.'

In [50]:
#함수 지정: for문, if문 미포함

def array_max(n,m,k,arr):
    arr = sorted(arr, reverse = True)
    x, y = divmod(m,k)
    
    if y == 0:
        total = total = sum(arr[:x])*k
    else:
        total = sum(arr[:x])*k + arr[x]*y
    
    return f'요소당 최대 덧셈 횟수가 {k}번, 총 덧셈 횟수가 {m}번 일 때, 주어진 배열을 가지고 만들 수 있는 최대값은 {total}입니다.'

In [51]:
import numpy as np

#함수 인자값을 제대로 받을 때까지 돌리자
while True:     
    x = input('>> 배열 요소의 수, 덧셈할 횟수, 최대 덧셈이 가능한 횟수를 공백으로 분리하여 입력하세요.\n')
    n = int(x.split(' ')[0])
    m = int(x.split(' ')[1])
    k = int(x.split(' ')[2])
    
    if n <= m//k and m % k >= 1:       
        print(f'※경고: 배열 요소의 수를 {m//k+1} 이상의 값으로 입력해주세요')      
        continue
    else:
        break
        
        
#배열 요소값을 제대로 받을 때까지 돌리자
while True:     
    y = input('>> 배열의 요소를 공백으로 분리하여 입력하세요.\n')
    arr = np.array([int(i) for i in y.split(' ')])

    
    if len(arr) != n:    #배열 요소의 개수가 입력값과 다른 경우
        print(f'※경고: 배열 요소의 수를 {n}개가 되도록 입력해주세요')
        continue    
    
    #배열 요소의 개수가 입력값과 같은 경우 
    elif len(set(arr)) == m//k and m%k > 0:   #고유 요소 개수가 총 덧셈 횟수를 최대 덧셈 횟수로 나눴을 때와 같은 경우
            print(f'※경고: 고유한 요소가 {m//k+1}개 이상 되도록 입력해주세요.')
            continue
    elif len(set(arr)) < m//k:  #고유 요소 개수가 총 덧셈 횟수를 최대 덧셈 횟수로 나눴을 때보다 작은 경우
        if m%k >= 1: 
            print(f'※경고: 고유한 요소가 {m//k+1}개 이상 되도록 입력해주세요.')
            continue
        elif m%k == 0: 
            print(f'※경고: 고유한 요소가 {m//k}개 이상 되도록 입력해주세요.')
            continue
    else:
        break

array_max(n,m,k,arr)  


>> 배열 요소의 수, 덧셈할 횟수, 최대 덧셈이 가능한 횟수를 공백으로 분리하여 입력하세요.
2 10 5
>> 배열의 요소를 공백으로 분리하여 입력하세요.
1 2


'요소당 최대 덧셈 횟수가 5번, 총 덧셈 횟수가 10번 일 때, 주어진 배열을 가지고 만들 수 있는 최대값은 15입니다.'

#### Q58. N개의 요소로 이루어진 배열이 있을 때 주어진 수들을 M번 더하여 가장 큰 수를 만드는 프로그램을 작성하세요. 단 배열의 특정한 인덱스(번호)에 해당하는 수가 연속해서 K번을 초과하여 더해질 수 없는 것이 특징이다.
프로그램은 다음 조건을 만족하는 N, M, K를 공백으로 일차 입력하고 N개의 배열을 공백으로 이차 입력하면 결과물을 출력하는 방식으로 수행함.
- 2 <= N <= 1000
- 1 <= M <= 10000
- 1 <= K <= 10000


In [ ]:
# N, M, K를 공백을 기준으로 구분하여 입력 받기
n, m, k = map(int, input().split())
# N개의 수를 공백을 기준으로 구분하여 입력 받기
data = list(map(int, input().split()))

data.sort() # 입력 받은 수들 정렬하기
first = data[n - 1] # 가장 큰 수
second = data[n - 2] # 두 번째로 큰 수

# 가장 큰 수가 더해지는 횟수 계산
count = m // (k + 1) * k
count += m % (k + 1)

result = 0
result += (count) * first # 가장 큰 수 더하기
result += (m - count) * second # 두 번째로 큰 수 더하기

print(result) # 최종 답안 출력

# 08/05

#### Q61. file1, 2의 파일 크기를 각각 구하세요.

- file1 = 'data/stockcode.txt'
- file2 = 'data/img_sample.jpg'

In [21]:
from pathlib import Path

Path(r'C:/cakd7/강의/m1_programming/dataset/stockcode.txt').stat()

os.stat_result(st_mode=33206, st_ino=13229323905746951, st_dev=2550895225, st_nlink=1, st_uid=0, st_gid=0, st_size=16339, st_atime=1659914591, st_mtime=1659660150, st_ctime=1659660150)

- st_mode: 파일 유형 및 파일 모드 비트(권한)
- st_ino: 윈도우에서 파일 인덱스를 나타냄
- st_dev: 파일이 있는 장치의 식별자를 나타냄
- st_nlink: 하드 링크의 수를 나타냄
- st_uid: 파일 소유자의 사용자 식별자를 나타냄
- st_gid: 파일 소유자의 그룹 식별자를 나타냄
- st_atime: 최근 액세스한 시간(초단위)
- st_mtime: 최근 컨텐츠를 수정한 시간
- st_ctime:  윈도우에서는 생성시간을 타나냄

In [18]:
#방법1

from pathlib import Path


file_size = Path(r'C:/cakd7/강의/m1_programming/dataset/stockcode.txt').stat().st_size
print(f'stockcode.txt의 파일크기는 {file_size: ,} 바이트 입니다.')

file_size2 = Path(r'C:/cakd7/강의/m1_programming/dataset/img_sample.jpg').stat().st_size
print(f'img_sample.jpg의 파일크기는 {file_size2: ,} 바이트 입니다.')

stockcode.txt의 파일크기는  16,339 바이트 입니다.
img_sample.jpg의 파일크기는  170,005 바이트 입니다.


In [19]:
#방법2

import os

file_size = os.path.getsize('C:/cakd7/강의/m1_programming/dataset/stockcode.txt')
print(f'stockcode.txt의 파일크기는 {file_size: ,} 바이트 입니다.')

file_size2 = os.path.getsize('C:/cakd7/강의/m1_programming/dataset/img_sample.jpg')
print(f'img_sample.jpg의 파일크기는 {file_size2:,} 바이트 입니다.')

stockcode.txt의 파일크기는  16,339 바이트 입니다.
img_sample.jpg의 파일크기는 170,005 바이트 입니다.


In [20]:
#방법3

import os

file_size = os.stat(r'C:/cakd7/강의/m1_programming/dataset/stockcode.txt').st_size
print(f'stockcode.txt의 파일크기는 {file_size: ,} 바이트 입니다.')

file_size2 = os.stat(r'C:/cakd7/강의/m1_programming/dataset/img_sample.jpg').st_size
print(f'img_sample.jpg의 파일크기는 {file_size2: ,} 바이트 입니다.')

stockcode.txt의 파일크기는  16,339 바이트 입니다.
img_sample.jpg의 파일크기는  170,005 바이트 입니다.


#### Q62.stockcode.txt의 105바이트 위치에서 500바이트를 읽어 그 내용은 stock_part.txt에 저장 한 후 출력하세요.


In [10]:
with open('C:/cakd7/강의/m1_programming/dataset/stockcode.txt','rb') as fr:                    #바이트 타입으로 읽기
    with open('stock_part.txt','wb') as fw:            #바이트 타입으로 쓰기
        fr.seek(105)     #105바이트에 위치하는 곳에 커서 이동
        fw.write(fr.read(500))     #500글자만 읽어서 쓰도록
        print(fr.tell())        #현재 커서가 위치하는 곳

605


In [11]:
#500바이트가 맞는지 확인
import os

os.stat(r'stock_part.txt').st_size

500

In [12]:
#내용 확인

with open('stock_part.txt', 'r') as fr:
    print(fr.read())

 유한양행
000101 유한양행우
000120 대한통운
000140 하이트홀딩스
000141 하이트홀딩스우
000150 두산
000151 두산우
000152 두산2우B
000180 성창기업지주
000210 대림산업
000211 대림산업우
000220 유유제약
000221 유유제약1우
000222 유유제약2우B
000230 일동제약
000240 한국타이어
000270 기아차
000300 대유신소재
000320 디피아이홀딩스
000321 디피아이홀딩스우
000322 디피아이홀딩스2B
000360 삼환기업
000361 삼환기업우
000370 한화손해보험
000390 삼화페인트
000400 롯데손해보험
000420 로


#### Q63.네이버 검색에서 관심 주제와 기사 수를 입력하면 그만큼 출력하는 크롤링 프로그램을 작성하여 다음 사항을 수행하세요.

기사 제목과 링크를 데이터프레임으로 가져온 후 본문 내용에서 한글 단어만 출력하여 형태소 분석
최근 국내 'AI'와 관련하여 가장 많이 언급되는 단어에 대한 빈도분석 및 시각화
AI 분야에서의 유의할 만한 트랜드 정보 및 인사이트 도출



In [27]:
import requests
import urllib
from bs4 import BeautifulSoup as BS
import pandas as pd

# 페이지 구조
## 1p-> '&start=01'
## 2p-> '&start=11'
## 3p-> '&start=21' 

In [28]:
query = input('> 검색 키워드를 입력해주세요\n')
n = int(input('> 필요한 뉴스기사 수를 입력해주세요\n'))

# 검색어를 문자 -> 퍼센트 인코딩
url='https://search.naver.com/search.naver?where=news&sm=tab_jum&query='
query = urllib.parse.quote(query)     


#### 한 페이지당 기사가 10개씩 존재함

ten_n, one_n = divmod( n, 10)
if one_n !=0:
    ten_n += 1
    
# ten_n = n // 10 +1    #### ex) 35개의 뉴스 타이틀을 긁어오기 위해 4페이지의 5번째까지 긁어와야함
# one_n = n % 10


news_title = []
news_url=[]

for i in range(ten_n):
    
    #크롤링할 url 지정
    query_url = url+query+'&start='+str(i)+'1'
    
    #페이지 소스 크롤링
    res = requests.get(query_url)
    html = res.content
    bs = BS(html, 'html.parser')
    
    #마지막 페이지 소스 크롤링 개수 제한
    if i == (ten_n-1):
        a_url = bs.find_all('a', class_='news_tit', limit = one_n)
    else:
        a_url = bs.find_all('a', class_='news_tit')
        
    for a in a_url:
        news_title.append(a.text)
        news_url.append(a.get('href'))
        
#데이터프레임 만들기
news_df = pd.DataFrame(columns = ['title', 'url'])
news_df['title'] = news_title
news_df['url'] = news_url
#     news_df['descriptions'] = description
 
news_df.index =  news_df.index +1
news_df


> 검색 키워드를 입력해주세요
ai
> 필요한 뉴스기사 수를 입력해주세요
10


title  \
1                       AI로 신소재 개발 속도 높인다   
2    “AI가 로또번호 예측” 가짜 후기로 600억원 가로챈 조직 검거   
3                  잡코리아 ‘AI 추천&검색 서비스’ 론칭   
4        카카오벤처스 "AI 임상시험 분석기업 액트노바에 시드투자"   
5   비투엔, 광주에 AI융합센터 개소···내년 디지털헬스 서비스 선보여   
6                하렉스인포텍 "가맹점주에 AI 맞춤 서비스"   
7            SKT 고객 절반이 5G…"AI·구독과 연계 강화"   
8                 경남TP-인제대 AI복합교육장 활성화 협약   
9           [AI-META 시대 '미래전략'] <28>AI 윤리   
10        [경남소식] 도 교육청 'AI시대 대비' 수학 교사 연수   

                                                  url  
1       http://www.fnnews.com/news/202208091117408193  
2   https://biz.chosun.com/topics/topics_social/20...  
3         https://www.sedaily.com/NewsView/269QB4Z3A3  
4   https://www.yna.co.kr/view/AKR2022080903130001...  
5         https://zdnet.co.kr/view/?no=20220809172036  
6   http://news.mk.co.kr/newsRead.php?no=702316&ye...  
7   https://www.hankyung.com/it/article/2022080906511  
8   http://news.mt.co.kr/mtview.php?no=20220809162...  
9                http://www.etnews.com/20220809000093  
10  https://www.yna.co.kr/view/AKR2022080913110005...

In [29]:
for i in news_df['url']:
    print(i)

http://www.fnnews.com/news/202208091117408193
https://biz.chosun.com/topics/topics_social/2022/08/09/P2BUCRQ3DRDVVHU3HSWUI4JRXU/?utm_source=naver&utm_medium=original&utm_campaign=biz
https://www.sedaily.com/NewsView/269QB4Z3A3
https://www.yna.co.kr/view/AKR20220809031300017?input=1195m
https://zdnet.co.kr/view/?no=20220809172036
http://news.mk.co.kr/newsRead.php?no=702316&year=2022
https://www.hankyung.com/it/article/2022080906511
http://news.mt.co.kr/mtview.php?no=2022080916263479746
http://www.etnews.com/20220809000093
https://www.yna.co.kr/view/AKR20220809131100052?input=1195m


In [38]:
import re

description = []
headers = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"}

for url in news_url:
    
    res2 = requests.get(url, headers = headers)
    html = res2.content
    bs = BS(html, 'html.parser')
    div = bs.find_all('div')
    
    
    # 본문은 거의 '~다.' 형식으로 끝나기 때문에 크롤링한 p태그에서 해당 형태만 추출함
    for d in div:  
        des = ''
        d = re.findall('.*다[.]',str(d))
    
        #일치하는 부분이 없을 때
        if len(d) == 0:
            new_p = ''
        
        #일치하는 부분이 있을 때
        if len(d) > 0:
            new_p = ''
            for i in p:
                i = re.sub('.*니다[.]','',i)    # '~니다.'의 경우는 광고, 경고문 등에 해당하기 때문에 삭제
                new_p += i

        new_p = re.sub('<.*>',' ',new_p)     #태그 삭제
#         new_p = re.sub('\(.*\)',' ',new_p)
#         new_p = re.sub('\[.*\]',' ',new_p)
#         new_p = re.sub('\s{1,}',' ',new_p)     
        des += new_p
        print(des)

In [ ]:
import re
import requests 
from bs4 import BeautifulSoup
import pandas as pd
from collections import Counter
import seaborn as sns
from konlpy.tag import Okt
from wordcloud import WordCloud
import matplotlib.pyplot as plt
from matplotlib import rc


rc('font', family='AppleGothic')
plt.rcParams['axes.unicode_minus'] = False

# 기사 제목과 본문 모두 워드 클라우드로 분석
for i in ['title','text']:
    print(i)
    title_list = news_df[i].tolist()
    text = ' '.join(title_list)
    text = re.sub('[^0-9가-힣]+',' ',text)
    # 한글자 이상의 명사만 뽑아냄
    okt = Okt()
    morph = okt.pos(text)
    noun_list = []
    for word, tag in morph:
        if (tag == 'Noun') & (len(word) > 1):
            noun_list.append(word)

    # 불용어 list 처리
    # 불용어 링크 : https://www.ranks.nl/stopwords/korean
    with open('./datasets/stopwords.txt', "r") as f:
        stop_words = f.readlines()
    stop_words = "".join(stop_words)
    stop_words = stop_words.split('\n')
    noun_list = [noun for noun in noun_list if not noun in stop_words]
    # 단어 빈도수 세기
    count = Counter(noun_list)
    data = dict(count.most_common())
    series = pd.Series(data)
    df = pd.DataFrame(series, columns=['cnt'])
    df10 = df.sort_values(by='cnt',ascending=False)[:10]
    df10.reset_index(inplace=True)
    display(df10)
    # 단어 빈도수 바 플롯
    display(sns.barplot(y='index', x='cnt', data=df10, orient='h'))
    plt.show();
    wordcloud = WordCloud(font_path='../visualization/dataset/malgun.ttf', background_color='white',
                         colormap='flare',width=2500,height=1800).generate_from_frequencies(data)

    plt.imshow(wordcloud)
    plt.axis('off')
    plt.show();
    print('-'*50)
        

#### Q64.어떠한 양의 정수 N이 1이 될 때까지 다음의 두 과정 중 하나를 반복적으로 선택하여 수행하려고 한다. 단 두번째 연산은 N이 K로 나누어 떨어질 때만 선택할 수 있다.  N과 K를 입력했을 때 N이 1이 될 때까지 1번 혹은 2번의 과정을 수행해야 하는 최소 횟수를 구하는 프로그램을 완성하세요.

1. N에서 1을 뺀다.
2. N을 K로 나눈다.


In [45]:
x = input('>> 양의 정수 N과 K를 입력해주세yo\n').split(' ')

n = int(x[0])
k = int(x[1])

def gotoone(n, k):
    cnt1 = 0
    cnt2 = 0
    
    while True:        
        if n % k == 0:
            n = n // k
            cnt2 += 1
        else:
            n -= 1
            cnt1 += 1
        if n != 1:
            continue
        
        return f"입력값이 1이 될 때까지 1번 연산을 '{cnt1}번', 2번 연산을 '{cnt2}번', 최소 '{cnt1 + cnt2}번' 수행해야합니다."
    
gotoone(n,k)

>> 양의 정수 N과 K를 입력해주세yo
150 3


"입력값이 1이 될 때까지 1번 연산을 '5번', 2번 연산을 '4번', 최소 '9번' 수행해야합니다."

#### Q65. 다음과 같이 출력되도록 만드세요.

In [1]:
'''
*
**
***
****
*****
'''

'\n*\n**\n***\n****\n*****\n'

In [2]:
for i in range(1,6):
    print('*'*i)

*
**
***
****
*****


#### Q66. 다음과 같이 출력되도록 만드세요.

In [3]:
'''
     * 
    ***
   *****
  *******
 *********
  *******
   *****
    ***
     *
'''

'\n     *\n    ***\n   *****\n  *******\n *********\n  *******\n   *****\n    ***\n     *\n'

In [12]:
for i in range(1,10,2):
    print(' '*int((9-i)/2),'*'*i,' '*int((9-i)/2))
for i in range(7,0,-2):
    print(' '*int((9-i)/2),'*'*i,' '*int((9-i)/2))

     *     
    ***    
   *****   
  *******  
 ********* 
  *******  
   *****   
    ***    
     *     


#### Q67. Tree 높이를 입력하면 만들어주는 프로그램을 만드세요.

In [4]:
'''
         *
        ***
       *****
      *******
     *********
    ***********
   *************
  ***************
 *****************
*******************
        ***
        ***
        ***
'''

'\n         *\n        ***\n       *****\n      *******\n     *********\n    ***********\n   *************\n  ***************\n *****************\n*******************\n        ***\n        ***\n        ***\n'

In [18]:
n = int(input('>> 나무의 높이를 입력하세요.\n'))

def tree(n):
    root = int(n*0.2)   
    height = n - root    

    leaves_width = 2*height+1     
    for i in range(height):
        leaf_width = 2*i+1

        blank =  int((leaves_width-leaf_width)/2)
        print(blank*' ',leaf_width *'*',blank*' ')

    root_width = int(leaves_width*0.3)
    for j in range(root):
        blank = int(((height*2+1)-root_width)/2)
        print(blank*' ', root_width*'*', blank*' ')
        
tree(n)

>> 나무의 높이를 입력하세요.
10
         *         
        ***        
       *****       
      *******      
     *********     
    ***********    
   *************   
  ***************  
       *****       
       *****       


In [14]:
n = int(input('>> 나무의 높이를 입력하세요.\n'))

def treemake(n):
    root = int(n*0.2)   
    height = n - root    

    leaves_width = 2*height+1     
    for i in range(height):
        leaf_width = 2*i+1

        blank =  int((leaves_width-leaf_width)/2)
        print(blank*' ',leaf_width *'*')

    root_width = int(leaves_width*0.3)
    for j in range(root):
        blank = int(((height*2+1)-root_width)/2)
        print(blank*' ', root_width*'*')
        
treemake(n)

>> 나무의 높이를 입력하세요.
20
                 *
                ***
               *****
              *******
             *********
            ***********
           *************
          ***************
         *****************
        *******************
       *********************
      ***********************
     *************************
    ***************************
   *****************************
  *******************************
             *********
             *********
             *********
             *********


#### Q68. 구구단을 출력하는 프로그램 작성하세요

In [ ]:
#함수로 여러 인자 받아서 출력하기

def gugudan(*n):
    for i in n:
        print(f'***** {i}단 *****')
        for j in range(1,10):
            print(f'{i} x {j} = {i*j}')
        print('\n')
    

gugudan(2,3)

In [1]:
#입력값 받아서 함수에 적용

n = input('>> 원하는 구구단의 숫자를 입력해주세요\nex)2,3\n')

def gugudan(n:str):
    n_list = n.split(',')

    for i in n_list:
        i = int(i)
        print(f'***** {i}단 *****')
        
        for j in range(1,10):
            print(f'{i} x {j} = {i*j}')
        print('\n')

print('\n')
gugudan(n)

>> 원하는 구구단의 숫자를 입력해주세요
ex)2,3
3,4,5


***** 3단 *****
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27


***** 4단 *****
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36


***** 5단 *****
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45




#### Q69. 아래와 같이 입력하면 N X M 행렬 형태의 숫자 카드 중에서 먼저 뽑고자 하는 카드가 포함되어 있는 행을 선택한 후 그 행에서 가장 숫자가 낮은 카드를 뽑아야 하는 규칙하에서 가장 높은 숫자가 쓰인 카드 한장의 숫자를 출력하는 프로그램을 작성하세요. 
- 첫번째 입력 : N X M 형열에 대하여 N(행), M(열)의 개수를 공백을 기준으로 입력(1<= N, M<=100)
- 두번째 입력 : 각 행의 숫자를 공백을 기준으로 입력. 단, 각 숫자는 1 이상 10000 이하의 자연수임.


1. 행열, 배열 요소 인자값 받아서 배열 만들기
2. 배열의 행기준 가장 작은 값 반환
3. 반환된 값들 중 가장 큰 값을 최종적으로 반환

In [17]:
#방법1

import numpy as np

nm = input('>> 만들고자 하는 행, 열의 숫자를 공백으로 분리하여 입력하세요.\n')
arr_str = input('>> 행, 열의 개수에 해당하는 요소를 공백으로 분리하여 입력하세요.\n')

def arr_maxofmin(nm,arr_str):
    n,m = [ int(i) for i in nm.split()]
    arr_str = [ int(i) for i in arr_str.split()]
    arr = np.array(arr_str).reshape(n,m)
    
    return f' 입력하신 배열의 각 행의 최솟값 중 최댓값은 "{a.min(axis = 1).max()}" 입니다.'

arr_maxofmin(nm, arr_str)

>> 만들고자 하는 행, 열의 숫자를 공백으로 분리하여 입력하세요.
3 3
>> 행, 열의 개수에 해당하는 요소를 공백으로 분리하여 입력하세요.
1 2 3 4 5 6 7 8 9


' 입력하신 배열의 각 행의 최솟값중 최댓값은 "7" 입니다.'

In [21]:
#방법2

import numpy as np

n,m = map(int, input('>>만들고자 하는 행, 열의 숫자를 공백으로 분리하여 입력하세요.\n').split())
arr_ele = list(map(int, input('>> 행, 열의 개수에 해당하는 요소를 공백으로 분리하여 입력하세요.\n').split()))

arr = np.array(arr_ele).reshape(n,m)

for i in range(len(arr)):
    ar_m = arr[i].min()
    print(f'{i+1}행: {ar_m}')

>>숫자를 입력하세요4 5
>> 행, 열의 개수에 해당하는 요소를 공백으로 분리하여 입력하세요.
1 3 4 5 8 55 44 1 3 4 5 8 10 55 165 10 55 165 11 22
0행: 1
1행: 1
2행: 5
3행: 10


#### Q69_2. 혼자 응용해보기

1. 배열 만들기
2. 최댓값 가진 행 뽑기
3. 최댓값 가진 행의 최솟값 추출

In [29]:
import numpy as np

nm = input('>> 만들고자 하는 행, 열의 숫자를 공백으로 분리하여 입력하세요.\n')
arr_str = input('>> 행, 열의 개수에 해당하는 요소를 공백으로 분리하여 입력하세요.\n')

def arr_n_min(nm, arr_str):
    n,m = [ int(i) for i in nm.split(' ') ]    #행열 공백분리 후 숫자화
    arr = np.array([ int(i) for i in arr_str.split(' ') ]).reshape(n,m)   #배열요소 공백분리 후 숫자화하여 배열화
    arr_n, arr_m = np.where(arr == arr.max())    #배열의 최댓값 인덱스 찾기 
    
    return arr[arr_n].min()      #최댓값이 존재하는 행의 최솟값 반환
    
arr_n_min(nm, arr_str)

>> 만들고자 하는 행, 열의 숫자를 공백으로 분리하여 입력하세요.
4 5
>> 행, 열의 개수에 해당하는 요소를 공백으로 분리하여 입력하세요.
1 3 4 5 8 55 44 1 3 4 5 8 10 55 165 10 55 165 11 22


5

#### Q70.아래와 같이 입력하면 N X M 행렬 형태의 숫자 카드 중에서 먼저 뽑고자 하는 카드가 포함되어 있는 행을 선택한 후 그 행에서 가장 숫자가 낮은 카드를 뽑아야 하는 규칙하에서 가장 높은 숫자가 쓰인 카드 한장의 숫자를 출력한는 프로그램을 작성하세요.  Q69는 MIN/MAX함수, 정렬 등의 방법으로 문제를 풀었다. 이 문제를 다중 for문을 사용하여 풀어보기
- 첫번째 입력 : N X M 형열에 대하여 N(행), M(열)의 개수를 공백을 기준으로 입력(1<= N, M<=100)
- 두번째 입력 : 각 행의 숫자를 공백을 기준으로 입력. 단, 각 숫자는 1 이상 10000 이하의 자연수임.


In [7]:
import numpy as np

nm = input('>> 만들고자 하는 행, 열의 숫자를 공백으로 분리하여 입력하세요.\n')
arr_str = input('>> 행, 열의 개수에 해당하는 요소를 공백으로 분리하여 입력하세요.\n')

def arr_maxofmin2(nm, arr_str):
    n,m = [int(i) for i in nm.split()]
    arr = np.array([int(i) for i in arr_str.split()]).reshape(n,m)

    y_max = 0
    for i in range(n):
        x_min = 10001
        x_max = 0

        for j in range(m):
            if arr[i,j]<x_min:
                x_min = arr[i,j]
        y_min = x_min

        if y_min > y_max:
            y_max = y_min

    return y_max


arr_maxofmin2(nm, arr_str)

>> 만들고자 하는 행, 열의 숫자를 공백으로 분리하여 입력하세요.
4 5
>> 행, 열의 개수에 해당하는 요소를 공백으로 분리하여 입력하세요.
1 3 4 5 8 55 44 1 3 4 5 8 10 55 165 10 55 165 11 22


10

In [11]:
#4 5
#1 3 4 5 8 55 44 1 3 4 5 8 10 55 165 10 55 165 11 22
arr

array([[  1,   3,   4,   5,   8],
       [  1,   3,   4,  44,  55],
       [  5,   8,  10,  55, 165],
       [ 10,  11,  22,  55, 165]])

#### Q71. 여행가 A는 N X N 크기의 정사각형 공간에 서 있다. A는 6개의 이동 명령 계획에 따라 움직이게 된다. 이동 명령은 L(왼쪽), R(오른쪽), U(윗쪽), D(아랫쪽)로 구성되며 R R R U D D와 같이 6개이다. 정사각형 공간을 벗어나는 움직임은 무시된다. 언급한 규칙에 따라 N과 이동 명령 계획으로 각각 5와 R R R U D D를 입력하면 A의 공간 좌표는 3 4가 된다. 이동 명력 계획서가 주어질 때 A가 최종적으로 도착할 지점의 좌표를 출력하는 프로그램을 작성하시오.


1. 이동명령 수 입력
2. 이동명령 입력
3. 정사각형을 벗어나지 않도록 명령어를 주어 최종 좌표를 반환하라

In [21]:
n = int(input('>> 정사각형의 너비를 입력하세요.\n'))
move = input('>> 이동명령어를 입력하세요.\n').split()

def square(n, move):
    x1 =1
    x2 =1
    for m in move:
        if (m == 'R') and (x1 < n) :
            x1 += 1
        elif (m == 'L') and (x1 > 1):
            x1 -= 1
        elif (m == 'U') and (x2 > 1):
            x2 -= 1
        elif (m == 'D') and (x2 < n):
            x2 += 1

    return f'최종 좌표는 "{(x1,x2)}"입니다.'

square(n, move)

>> 정사각형의 너비를 입력하세요.
70
>> 이동명령어를 입력하세요.
R R R R R R R R R U U U U U D D D D D D D D


'최종 좌표는 "(10, 9)"입니다.'

#### Q72. 정수 N이 입력되면 00시 00분 00초부터 N시 59분 59초까지의 모든 시각 중에서 3이 하나라도 포함되는 모든 경우의 수를 구하는 프로그램을 작성하시오.(0<= N <=23)


```
7입력 시 14625번 포함됨이 반환
```

In [6]:
n = int(input('>> 시간을 입력하세요\n'))

def time_three(n):
    total = 0

    for i in range(n+1):
        for j in range(60):
            for k in range(60):
                if (str(i) + str(j) + str(k)).find('3') != -1:
                    total += 1
    
    return total


time_three(n)

>> 시간을 입력하세요
7


14625

#### Q73. 행 위치는 1~8로 열 위치는 a ~ h로 표현하는 8 x 8 좌표 평면상에서 특정 위치가 주어졌을 때 아래 조건하에서 그 위치에서 이동할 수 있는 경우의 수를 출력하는 프로그램을 작성하세요.
- 수평으로 두 칸 이동한 뒤에 수직으로 한 칸 이동
- 수직으로 두 칸 이동한 뒤에 수평으로 한 칸 이동
- 8 x 8 좌표 평면을 나갈 수 없음


1. 오른쪽, 왼쪽, 위쪽, 아래쪽 공백 개수를 0,1,2이상으로 구분
2. 경우의수를 따져서 해당값 반환
3. 경우의 수
- 0개수, 1개수, 2개수
- 1: 경우의수 없음
- 2: 2, 0, 2
- 3: 1, 1, 2
- 4: 1, 0, 3
- 5: 경우의수 없음
- 6: 0, 1, 3
- 7: 경우의수 없음
- 8: 0, 0, 4

In [29]:
import numpy as np

que = input('>> 좌표를 입력하세요 \n')

def count_move(que):
    col = 'abcdefgh'.index(que[0])+1
    row = int(que[1])

    space = np.array([row-1, 8-row, col-1, 8-col])   #left, right, up, down
    space = list(np.where(space>2, 2, space))
    cnt_0, cnt_1,cnt_2 = space.count(0), space.count(1), space.count(2) 

    if cnt_2 ==2:
        if cnt_1 == 0:
            total = 2
        else: 
            total = 3
    elif cnt_2 == 3:
        if cnt_1 == 0:
            total = 4
        else: 
            total = 6
    elif cnt_2 == 4:
        total = 8
    
    #좌표
    xy = np.zeros((8,8)).astype(np.int64)
    xy[col-1, row-1] = 1
    print(xy)
    return f' 이동할 수 있는 경우의 수는 총 {total}개 입니다.'

count_move(que)

>> 좌표를 입력하세요 
b5
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


' 이동할 수 있는 경우의 수는 총 6개 입니다.'

#### Q74.
캐릭터는 매뉴얼에 따라 이동한다. 아래 입력조건에 따라 캐릭터가 방문한 칸의 수를 출력하는 프로그램을 작성하세요.

- 입력조건
  - 첫째 줄에 맵의 세로 크기 N과 가로 크기 M을 공백으로 구분하여 입력 (3 <= N,M <=50)
  - 둘째 줄에 게임 캐릭터가 있는 칸의 좌표 (A,B)와 바라보는 방향 d가 각각 서로 공백으로 구분하여 입력(방향 d의 값으로는 북, 동, 남, 서가 각각 0,1,2,3)
  - 셋째 줄에 맵이 육지인지 바다인지에 대한 정보 입력(육지 0, 바다 1) N개의 줄에 맵의 상태가 북쪽으로 부터 남쪽순서대로 각 줄의 데이터는 서쪽부터 동쪽 순서대로 주어진다.
  - 처음에 캐릭터가 위치한 칸의 상태는 항상 육지이다.


- 매뉴얼<BR>
  캐릭터가 있는 장소는 1 X 1 크기의 정사각형으로 이루어진 N X M 크기의 직사각형으로 각각의 칸은 육지 또는 바다이다.캐릭터는 동서남북 중 한 곳을 바라본다. 맵의 각 칸은 (A, B)로 나타낼 수 있고 A는 북쪽으로부터 떨어진 칸의 개수, B는 서쪽으로부터 떨어진 칸의 개수이다.캐릭터는 상하좌우로 움직일 수 있고 바다로 되어 있는 공간에는 갈 수 없다. 캐릭터의 움직임 설정을 위한 매뉴얼은 아래와 같다.
  - 현재 위치에서 현재 방향을 기준으로 왼쪽 방향부터 차례대로 갈 곳을 정한다.
  - 캐릭터의 바로 왼쪽 방향에 아직 가보지 않은 칸이 존재한다면 왼쪽 방향으로 회전한 다음 왼쪽으로 한 칸을 전진한다. 왼쪽 방향에 가보지 않은 칸이 없다면 왼쪽 방향으로 회전만 수행하고 1단계로 돌아간다.
  - 만약 네 방향 모두 이미 가본 칸이거나 바다로 되어 있는 칸인 경우에는 바라보는 방향을 유지한 채로 한 칸 뒤로 가고 1단계로 돌아간다. 단, 이때 뒤쪽 방향이 바다인 칸이라 뒤로 갈수 없는 경우에는 움직임을 멈춘다.


In [7]:
nm = input(">> 맵의 크기를 입력하세요.(가로 * 세로) \n ex)3 4\n")

pin = input(
'''>> 게임 캐릭터의 위치와 바라보는 방향을 입력하세요
     " 북 : 0,  동 : 1,  남 : 2,  서 : 3 "
''')

mapmap = input(
'''>> 맵 구성 요소를 입력하세요.(육지: 0, 바다: 1)
       ex) (4 * 4)
            " 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 0"
''')



# 4 4
# 0 0 2
# 1 1 1 1 1 0 0 1 1 0 0 1 0 1 1 1


#4 4
#1 1 2
#0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0


>> 맵의 크기를 입력하세요.(가로 * 세로) 
 ex)3 4
4 4
>> 게임 캐릭터의 위치와 바라보는 방향을 입력하세요
     " 북 : 0,  동 : 1,  남 : 2,  서 : 3 "
0 0 2
>> 맵 구성 요소를 입력하세요.(육지: 0, 바다: 1)
       ex) (4 * 4)
            " 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 0"
1 1 1 1 1 0 0 1 1 0 0 1 0 1 1 1


In [8]:
import numpy as np

n, m = int(nm.split()[0]), int(nm.split()[1])
x1, y1, d= int(pin.split()[0]), int(pin.split()[1]), int(pin.split()[2])
map_in = np.array([int(i) for i in mapmap.split()]).reshape(n,m)
print(map_in)

direction = [[-1,0], [0,1], [1,0], [0,-1]] # 북, 동, 남, 서

cnt = 0
doit = []
while True:
    d = (d+1) % 4
    xm, ym = direction[d][0], direction[d][1]
    
    #다 가봤으면..후..진..
    if doit == [True, True, True, True]:
        print(map_in)
        map_in[x1, y1] = 2
        x1 += (-1)*xm
        y1 += (-1)*ym
        print(map_in)
        cnt += 1
        
        print(map_in)
        break
        
    # 인덱스 범위가 벗어나는 경우 pass
    if (x1 + xm < 0) | (x1 + xm > n-1) | (y1 + ym < 0) | (y1 + ym > m-1):
        outof_index = True
        doit.append(outof_index)
        print('인덱스 벗어남')
        print(doit)
        continue  

    xy = map_in[x1 + xm, y1 + ym]
    print(xy)
    
    # 돌린 방향으로 직진 시 1이 나오는 경우 전진 + 지나온 곳 8 표시
    if xy == 1:
        map_in[x1, y1] = 8
        x1 += xm
        y1 += ym
        cnt += 1
        doit = []
        print(map_in)
        print('카운트: '+str(cnt))
        print(doit)
        continue 

    #이미 가봤던 곳, 바다는 pass
    elif ( xy == 8 ) or ( xy == 0 ):
        if ( xy == 8 ):
            already_go = True
            doit.append(already_go)
            print('이미 갔던 곳')
            print(doit)
        else:
            sea = True
            doit.append(sea)
            print('바다')
            print(doit)
        continue
    
print(map_in)
print(cnt)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [0 1 1 1]]
인덱스 벗어남
[True]
인덱스 벗어남
[True, True]
1
[[8 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [0 1 1 1]]
카운트: 1
[]
0
바다
[True]
8
이미 갔던 곳
[True, True]
인덱스 벗어남
[True, True, True]
1
[[8 8 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [0 1 1 1]]
카운트: 2
[]
0
바다
[True]
8
이미 갔던 곳
[True, True]
인덱스 벗어남
[True, True, True]
1
[[8 8 8 1]
 [1 0 0 1]
 [1 0 0 1]
 [0 1 1 1]]
카운트: 3
[]
1
[[8 8 8 8]
 [1 0 0 1]
 [1 0 0 1]
 [0 1 1 1]]
카운트: 4
[]
0
바다
[True]
8
이미 갔던 곳
[True, True]
인덱스 벗어남
[True, True, True]
1
[[8 8 8 8]
 [1 0 0 8]
 [1 0 0 1]
 [0 1 1 1]]
카운트: 5
[]
0
바다
[True]
8
이미 갔던 곳
[True, True]
인덱스 벗어남
[True, True, True]
1
[[8 8 8 8]
 [1 0 0 8]
 [1 0 0 8]
 [0 1 1 1]]
카운트: 6
[]
1
[[8 8 8 8]
 [1 0 0 8]
 [1 0 0 8]
 [0 1 1 8]]
카운트: 7
[]
0
바다
[True]
8
이미 갔던 곳
[True, True]
인덱스 벗어남
[True, True, True]
1
[[8 8 8 8]
 [1 0 0 8]
 [1 0 0 8]
 [0 1 8 8]]
카운트: 8
[]
0
바다
[True]
8
이미 갔던 곳
[True, True]
인덱스 벗어남
[True, True, True]
0
바다
[True, True, True, True]
[[8 8 8 8]
 [1 0 0 8]
 [1 0 0 8]
 [0 1 8 8]]
[[8 8 8 8]
 [1 0