#### Q75. N X M 크기의 얼음 틀로 한번에 만들 수 있는 아이스크림의 개수를 아래 입력조건에 따라 출력하는 프로그램을 DFS(Depth First Search)를 이용하여 작성하세요.
 
- 입력조건
  - 첫번째 줄에 얼음 틀의 세로 길이 N과 가로 길이 M이 주어진다.(1 <= N,M <= 1000)
  - 두번째 줄부터 N+1번째 줄까지 얼음 틀의 형태가 주어진다.
  - 이때 구멍이 뚫려있는 부분은 0 그렇지 않은 부분은 1이다.
  - 구멍이 뚫려 있는 부분끼리 상, 하, 좌, 우로 붙어 있는 경우 서로 연결되어 있는 것으로 간주한다.


* <b>DFS</b>
    - 깊이를 우선시 하여 탐색하는 방법 
    - '한 우물만 판다' 라는 느낌처럼 한 길만 계속 깊이 파고드는 방식
    <img src = "https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FoiVuV%2FbtqYusdiOdX%2FK4nhzcjlxt80MbIpWjsyrk%2Fimg.png" width = 400>
    
* <b>BFS</b>
    - 넓이를 우선시
    - 특정 노드와 연결된 모든 노드를 한번씩 거친 다음에 다음 노드로 이동하는 방식
    - 주로 최단거리를 구할 때 사용
    - 재귀적으로 동작하지 않음
    - 그래프 탐색의 경우 어떤 노드를 방문했었는지 여부를 반드시 검사해야 함
    <img src = "https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fni4Mn%2FbtqYn4EMNlG%2FVF5gXF41YWOfRGWoixkUT0%2Fimg.png" width = 400>
    
    
참고: https://lotuslee.tistory.com/48

============================스택, 큐 설명===========================

In [10]:
# 스택: 선입후출

stack = []
stack.append(5)
stack.append(2)
stack.append(3)
stack.append(7)
stack.pop(3)
stack.append(1)

stack

[5, 2, 3, 1]

In [20]:
# 큐: 선입선출
from collections import deque
queue = deque()

queue.append(5)
queue.append(2)
queue.append(3)
queue.append(7)
queue.popleft()
queue.append(1)
queue.append(4)
queue.popleft()

print(queue)

deque([3, 7, 1, 4])


========================================================================

##### 풀이
```
예시: 
nm = 5 5

00110
00011
11111
00111
11000

cnt = 4
```

In [22]:
import numpy as np

nm = input(">>n,m을 입력하세요.\n")
shape = input(">>얼음틀 모양을 입력하세요\n")

n, m = int(nm.split()[0]), int(nm.split()[1])
shape = np.array([ int(i) for i in shape.split()]).reshape(n,m)

# 5 5
# 0 0 1 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 0

>>n,m을 입력하세요.
5 5
>>얼음틀 모양을 입력하세요
0 0 1 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 0


In [23]:
n, m, shape

(5,
 5,
 array([[0, 0, 1, 1, 0],
        [0, 0, 0, 1, 1],
        [1, 1, 1, 1, 1],
        [0, 0, 1, 1, 1],
        [1, 1, 0, 0, 0]]))

In [24]:
# dfs함수 만들기
## 특정 노드 방문한 뒤에 연결된 모든 노드들 방문

def dfs(x,y):
    
    # 행렬 인덱스 값에서 벗어난 경우
    if x<0 or x>=n or y<0 or y>=m:
        return False
    
    # 행렬 인덱싱 값이 0인 경우(비어있는 틀인 경우) 채우기
    elif shape[x,y] == 0:
        shape[x,y] = 1    # stack 된 요소를 pop처리하는 것
        dfs(x,y-1)  # 왼  
        dfs(x,y+1)  # 오
        dfs(x-1,y)  # 아
        dfs(x+1,y)  # 위
        return True
    
    # 행렬 인덱싱 값이 1인 경우
    return False


cnt = 0
for i in range(n):
    for j in range(m):
        if dfs(i,j) == True:
            cnt += 1

print(f'채워야할 총 얼음 틀 개수: {cnt}')

채워야할 총 얼음 틀 개수: 4


#### Q76. 10!을 재귀함수를 이용해 출력하세요.

============================재귀함수 활용 예시===========================

In [28]:
def recursive_function(i):
    if i == 5:
        return 
    print(i, '번째 재귀함수에서', i+1, '번째 재귀함수를 호출합니다.')
    recursive_function(i+1)
    print(i, '번째 재귀함수를 호출합니다.')
    

In [29]:
recursive_function(1)

1 번째 재귀함수에서 2 번째 재귀함수를 호출합니다.
2 번째 재귀함수에서 3 번째 재귀함수를 호출합니다.
3 번째 재귀함수에서 4 번째 재귀함수를 호출합니다.
4 번째 재귀함수에서 5 번째 재귀함수를 호출합니다.
4 번째 재귀함수를 호출합니다.
3 번째 재귀함수를 호출합니다.
2 번째 재귀함수를 호출합니다.
1 번째 재귀함수를 호출합니다.


=====================================================================

In [39]:
# for문을 활용한 팩토리얼 계산

def factorial_iterative(n):
    result = 1
    for i in range(1,n+1):
        result *= i
    return result
    
factorial_iterative(10)

3628800

In [40]:
# 재귀함수를 활용한 팩토리얼 계산

def factorial(n):
    if n == 1:
        return 1
    else:
        return n * factorial(n-1)
    
factorial(10)

3628800

#### Q77. N X M 크기의 미로에는 여러마리의 괴물이 있어 이를 피해 탈출해야 한다. 주인공의 위치는 (0,0)이고 미로의 출구는 (N-1,M-1)의 위치에 존재하며 한번에 한칸씩 이동할 수 있다. 괴물이 있는 부분은 0, 없는 부분은 1로 표시되어 있으며 미로는 반드시 탈출할 수 있는 형태로 제시된다. 주인공이 탈출하기 위해 움직여야 하는 최소 칸의 개수를 구하세요. 칸을 셀 때는 시작 칸과 마지막 칸을 모두 포함하여 계산하고 입력 조건은 아래와 같다.(BFS를 이용)
- 첫째 줄에 두 정수 N,M(4<=N,M<=200)이 주어진다. 
- 다음 N개의 줄에는 각각 M개의 정수(0 혹은 1)로 미로의 정보가 주어진다. 각각의 수들은 공백없이 붙여서 입력으로 제시된다. 
- 또한 시작칸과 마지막칸은 항상 1이다.


참고: https://casa-de-feel.tistory.com/33

In [2]:
import numpy as np
import pandas as pd

# 입력값 받기
nm = list(map(int, input('>> 행, 열을 입력하세요. \n').split()))
n,m = nm[0], nm[1]

shape = np.array([ int(i) for i in input('>> 미로 구조를 입력하세요. \n').split() ]).reshape(n, m)

n,m,shape

# 5 5
# 1 1 0 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1

>> 행, 열을 입력하세요. 
5 5
>> 미로 구조를 입력하세요. 
1 1 0 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1


(5,
 5,
 array([[1, 1, 0, 1, 1],
        [0, 1, 0, 1, 1],
        [0, 1, 1, 1, 1],
        [1, 1, 0, 1, 1],
        [1, 0, 1, 1, 1]]))

참고: https://wooono.tistory.com/498

In [27]:
import numpy as np
import pandas as pd
from collections import deque

nm = list(map(int, input('>> 행, 열을 입력하세요. \n').split()))
n,m = nm[0], nm[1]

# 2차원 리스트의 맵 정보 입력 받기
shape = np.array([ int(i) for i in input('>> 미로 구조를 입력하세요. \n').split()]).reshape(n, m)


def bfs(x, y):
    queue = deque()
    queue.append([x,y])
    
    d = [[-1,0],[1,0],[0,-1],[0,1]] #상, 하, 좌, 우
    
    # queue가 빌 때까지 실행
    while queue:
        x, y = queue.popleft()
        
        # 상하좌우 다 살펴보기
        for i in range(4):
            xm = x + d[i][0]
            ym = y + d[i][1]

            # 미로 인덱스 범위를 벗어난 경우
            if xm < 0 or xm >=n or ym < 0 or ym >= m:
                continue

            # 괴물이 있는 경우
            if shape[xm, ym] == 0:
                continue

            # 괴물이 없는 길인 경우
            if shape[xm, ym] == 1:
                shape[xm, ym] = shape[x, y] + 1
                print(shape)
                queue.append([xm,ym])
            
    return f'미로를 빠져나가기 위해 이동한 칸 수: {shape[n-1, m-1]} 칸'

bfs(0,0)     

#####예시
# 5 5
# 1 1 0 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1

>> 행, 열을 입력하세요. 
5 5
>> 미로 구조를 입력하세요. 
1 1 0 1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1
[[1 2 0 1 1]
 [0 1 0 1 1]
 [0 1 1 1 1]
 [1 1 0 1 1]
 [1 0 1 1 1]]
[[1 2 0 1 1]
 [0 3 0 1 1]
 [0 1 1 1 1]
 [1 1 0 1 1]
 [1 0 1 1 1]]
[[3 2 0 1 1]
 [0 3 0 1 1]
 [0 1 1 1 1]
 [1 1 0 1 1]
 [1 0 1 1 1]]
[[3 2 0 1 1]
 [0 3 0 1 1]
 [0 4 1 1 1]
 [1 1 0 1 1]
 [1 0 1 1 1]]
[[3 2 0 1 1]
 [0 3 0 1 1]
 [0 4 1 1 1]
 [1 5 0 1 1]
 [1 0 1 1 1]]
[[3 2 0 1 1]
 [0 3 0 1 1]
 [0 4 5 1 1]
 [1 5 0 1 1]
 [1 0 1 1 1]]
[[3 2 0 1 1]
 [0 3 0 1 1]
 [0 4 5 1 1]
 [6 5 0 1 1]
 [1 0 1 1 1]]
[[3 2 0 1 1]
 [0 3 0 1 1]
 [0 4 5 6 1]
 [6 5 0 1 1]
 [1 0 1 1 1]]
[[3 2 0 1 1]
 [0 3 0 1 1]
 [0 4 5 6 1]
 [6 5 0 1 1]
 [7 0 1 1 1]]
[[3 2 0 1 1]
 [0 3 0 7 1]
 [0 4 5 6 1]
 [6 5 0 1 1]
 [7 0 1 1 1]]
[[3 2 0 1 1]
 [0 3 0 7 1]
 [0 4 5 6 1]
 [6 5 0 7 1]
 [7 0 1 1 1]]
[[3 2 0 1 1]
 [0 3 0 7 1]
 [0 4 5 6 7]
 [6 5 0 7 1]
 [7 0 1 1 1]]
[[3 2 0 8 1]
 [0 3 0 7 1]
 [0 4 5 6 7]
 [6 5 0 7 1]
 [7 0 1 1 1]]
[[3 2 0 8 1]
 [0 3 0 7 8]
 [0 4 5 6 7]
 [6 5 0 7 1]
 

'미로를 빠져나가기 위해 이동한 칸 수: 9 칸'

#### Q78. 소수란 2보다 큰 자연수 중에서 1과 자기자신을 제외한 자연수로는 나누어떨어지지 않는 자연수이다. 어떠한 자연수가 소수인지 아닌지 판별하는 프로그램을 작성하세요.

In [14]:
#방법1

def sosu(x):
    
    # 2부터 (x - 1)까지의 모든 수를 확인
    for i in range(2, x):
        
        # x가 해당 수로 나누어떨어진다면 소수가 아님
        if x % i == 0:
            return f'{x}은/는 소수가 아닙니다.' 
        
    return f'{x}은/는 소수입니다.'

print(sosu(55)) 

55은/는 소수가 아닙니다.


In [15]:
#방법2

def sosu2(x):
    is_divided = [ x % i for i in range(2,x) ]
    
    if len(is_divided) > 2:
        return f'{x}은/는 소수가 아닙니다.'
    else:
        return f'{x}은/는 소수입니다.'
    
print(sosu2(3))

3은/는 소수입니다.


#### Q79. M 이상 N 이하의 소수를 모두 출력하는 프로그램을 작성하세요.
- 입력조건
  - 첫째 줄에 자연수 M과 N이 빈칸을 사이에 두고 주어진다.(1<=M<=N<=1,000,000)
  - 단 M이상 N 이하의 소수가 하나 이상 있는 입력만 주어진다.


In [6]:
def isprime_all(x):
    if x == 1:
        return False
    else:
        for i in range(2, x-1):
            if x % i == 0:
                return False
        return True

n, m = map(int, input().split())

for i in range(n, m + 1):
    if isprime_all(i):
        print(i)

50 70
53
59
61
67


#### Q80.

암호는 서로 다른 L개의 알파벳 소문자들로 구성되며 최소 한 개의 모음(a, e, i, o, u)과 최소 두 개의 자음으로 구성되어 있다고 알려져 있다. 또한 정렬된 문자열을 선호하는 직원들의 성향으로 미루어 보아 암호를 이루는 알파벳이 암호에서 증가하는 순서로 배열되었을 것이라고 추측된다. 즉, abc는 가능성이 있는 암호이지만 bac는 그렇지 않다. 새 보안 시스템에서 직원들이 암호로 사용했을 법한 문자의 종류는 C가지가 있다고 한다. 이 알파벳을 입수한 james, kevin 형제는 직원들의 방에 침투하기 위해 암호를 추측해 보려고 한다. C개의 문자들이 모두 주어졌을 때, 가능성 있는 암호들을 모두 구하는 프로그램을 다음 사항에 유의하여 작성하시오.
- 첫째 줄에 두 정수 L, C가 주어진다. (3 ≤ L ≤ C ≤ 15) 다음 줄에는 C개의 문자들이 공백으로 구분되어 주어진다. 주어지는 문자들은 알파벳 소문자이며, 중복되는 것은 없다.
- 각 줄에 하나씩, 사전식으로 가능성 있는 암호를 모두 출력한다.
